version: '3'

services: 
    app:  
        build: 
            context: .
            dockerfile: Dockerfile
        container_name: userapp
        ports: 
            - '8080:8080'
        depends_on: 
        - postgres

    postgres:
        image: postgres
        container_name: userdb
        ports: 
          - '5440:5432'
        volumes: 
          - my_go_db:/var/lib/postgresql/data
        environment: 
          - POSTGRES_PASSWORD=1999  
         
volumes: 
    my_go_db:   