version: '3'
  
services: 
  app:  
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: go
    ports: 
      - '8080:8080'
    depends_on: 
      - postgres
    environment: 
      - SESSION_KEY

  postgres:
    image: postgres
    container_name: db
    ports: 
      - '5441:5432'
    environment: 
      - POSTGRES_PASSWORD=postgres
    volumes: 
      - my_go_db:/var/lib/postgresql/data

volumes: 
  my_go_db:        

