version: '3'

services: 
  app:  
    image: go_docker
    container_name: go
    build: .
    restart: on-failure
    depends_on: 
      - postgres

  postgres:
    image: postgres
    container_name: db
    ports: 
      - '5441:5432'
    environment: 
      - POSTGRES_PASSWORD=postgres
    volumes: 
      - my_go_db:/var/lib/postgresql/data

volumes: 
  my_go_db:        

