version: '3'
  
services: 
  app:  
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: go
    ports: 
      - '8080:8080'
    depends_on: 
      - postgres
    environment: 
      - SESSION_KEY

  postgres:
    image: postgres
    container_name: db
    ports: 
      - '5441:5432'
    environment: 
      - POSTGRES_PASSWORD=postgres
    volumes: 
      - my_go_db:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: db_redis 
    ports:
      - '6370:6379'
    environment: 
      - Password=7UY2dsFnaNxrhpTH5ZKQtCMq4AZrr4uR
      - Addr=165.227.151.146:6379
 

volumes: 
  my_go_db:        

