version: '3'
  
services: 
  app:  
    build: 
      context: .
      dockerfile: go.Dockerfile
    image: books_app  
    container_name: go
    ports: 
      - '8080:8080'
    depends_on: 
      - postgres
      - redis
  
  node:  
    build: 
      context: .
      dockerfile: node.Dockerfile
    image: node_app
    container_name: node
    ports: 
      - '4200:4200'
    depends_on: 
      - app 

  postgres:
    image: postgres
    container_name: db
    ports: 
      - '5441:5432'
    volumes: 
      - my_go_db:/var/lib/postgresql/data
    environment: 
      - POSTGRES_PASSWORD=postgres  

  redis:
    image: redis
    container_name: db_redis 
    ports:
      - '6379:6379'

volumes: 
  my_go_db:        

